# Generated by Django 5.0.4 on 2024-04-07 15:05

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Event',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('event_name', models.CharField(blank=True, max_length=50, null=True)),
                ('event_description', models.TextField(blank=True, max_length=500, null=True)),
                ('event_venue', models.CharField(blank=True, max_length=50, null=True)),
                ('event_start_date', models.DateTimeField(blank=True, max_length=50, null=True)),
                ('event_end_date', models.DateTimeField(blank=True, max_length=50, null=True)),
            ],
        ),
    ]
