# Generated by Django 5.0.4 on 2024-04-08 12:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_event_event_image'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tickets',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('ticket_name', models.CharField(blank=True, max_length=50, null=True)),
                ('max_capacity', models.PositiveIntegerField()),
                ('ticket_group', models.CharField(max_length=50, null=True)),
                ('price', models.DecimalField(decimal_places=3, max_digits=10)),
                ('discount_percentage', models.PositiveIntegerField()),
                ('open_time_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
                ('close_time_date', models.DateTimeField(blank=True, default=datetime.datetime.now)),
            ],
        ),
        migrations.AlterField(
            model_name='event',
            name='event_end_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_start_date',
            field=models.DateTimeField(blank=True, default=datetime.datetime.now),
        ),
    ]
