# Generated by Django 5.0.4 on 2024-04-24 13:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0004_ticketgroup_and_more'),
    ]

    operations = [
        migrations.DeleteModel(
            name='TicketGroup',
        ),
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.TextField(blank=True, default='fill', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(blank=True, max_length=50),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_venue',
            field=models.CharField(blank=True, max_length=50),
        ),
    ]
