# Generated by Django 5.0.4 on 2024-04-24 16:07

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0006_alter_event_event_name_alter_event_event_venue'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(blank=True, default='fill', max_length=500),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_venue',
            field=models.CharField(blank=True, default='fill', max_length=500),
        ),
    ]
