# Generated by Django 5.0.4 on 2024-04-24 18:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0002_event_event_image_alter_event_event_description_and_more'),
        ('mainapp', '0007_alter_event_event_name_alter_event_event_venue'),
    ]

    operations = [
    ]
