# Generated by Django 5.0.4 on 2024-04-25 17:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mainapp', '0008_merge_20240425_0009'),
    ]

    operations = [
        migrations.AlterField(
            model_name='event',
            name='event_description',
            field=models.TextField(blank=True, default='fill', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_image',
            field=models.TextField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_name',
            field=models.CharField(blank=True, default='fill', max_length=500, null=True),
        ),
        migrations.AlterField(
            model_name='event',
            name='event_venue',
            field=models.CharField(blank=True, default='fill', max_length=500, null=True),
        ),
    ]
